// Extended Strong's v8 — Healing/Miracles, Law/Torah, Exile/Return, Discipleship
export const EXTENDED_STRONGS_V8 = [
  // Hebrew — Law / Torah
  { id: 'H8451', original: 'תּוֹרָה', transliteration: 'torah', definition: 'Law, instruction, teaching — God\'s revealed will and instruction for life', language: 'hebrew' as const },
  { id: 'H4687', original: 'מִצְוָה', transliteration: 'mitsvah', definition: 'Commandment, precept — a specific divine command or obligation', language: 'hebrew' as const },
  { id: 'H2706', original: 'חֹק', transliteration: 'choq', definition: 'Statute, ordinance, decree — an appointed regulation or boundary', language: 'hebrew' as const },
  { id: 'H4941', original: 'מִשְׁפָּט', transliteration: 'mishpat', definition: 'Justice, judgment, ordinance — a legal decision, right, or proper order', language: 'hebrew' as const },
  { id: 'H5715', original: 'עֵדוּת', transliteration: 'edut', definition: 'Testimony, witness — the covenant stipulations, tablets of testimony', language: 'hebrew' as const },
  { id: 'H6490', original: 'פִּקּוּד', transliteration: 'piqqud', definition: 'Precept, mandate — God\'s authoritative instructions for conduct', language: 'hebrew' as const },
  // Hebrew — Exile / Return
  { id: 'H1540', original: 'גָּלָה', transliteration: 'galah', definition: 'To uncover, reveal, go into exile — deportation from homeland', language: 'hebrew' as const },
  { id: 'H7622', original: 'שְׁבוּת', transliteration: 'shevut', definition: 'Captivity, restoration — the state of exile or its reversal', language: 'hebrew' as const },
  { id: 'H7725', original: 'שׁוּב', transliteration: 'shuv', definition: 'To return, turn back, repent — physical return and spiritual turning', language: 'hebrew' as const },
  { id: 'H1129', original: 'בָּנָה', transliteration: 'banah', definition: 'To build, rebuild, establish — construction, restoration of temple/city', language: 'hebrew' as const },
  { id: 'H2820', original: 'חָשַׂךְ', transliteration: 'chasak', definition: 'To withhold, restrain, spare — God withholding judgment or wrath', language: 'hebrew' as const },
  { id: 'H5162', original: 'נָחַם', transliteration: 'nacham', definition: 'To comfort, console, repent — divine comfort after suffering', language: 'hebrew' as const },
  // Hebrew — Healing / Miracles
  { id: 'H7495', original: 'רָפָא', transliteration: 'rapha', definition: 'To heal, cure, repair — divine and physical healing', language: 'hebrew' as const },
  { id: 'H4159', original: 'מוֹפֵת', transliteration: 'mophet', definition: 'Wonder, sign, portent — miraculous demonstration of divine power', language: 'hebrew' as const },
  { id: 'H6381', original: 'פָּלָא', transliteration: 'pala', definition: 'To be wonderful, marvelous — surpassing ordinary, miraculous acts', language: 'hebrew' as const },
  { id: 'H3444', original: 'יְשׁוּעָה', transliteration: 'yeshuah', definition: 'Salvation, deliverance, rescue — God\'s saving intervention', language: 'hebrew' as const },
  { id: 'H2421', original: 'חָיָה', transliteration: 'chayah', definition: 'To live, revive, restore to life — life-giving power of God', language: 'hebrew' as const },
  // Greek — Healing / Miracles
  { id: 'G2323', original: 'θεραπεύω', transliteration: 'therapeuo', definition: 'To heal, cure, serve — therapeutic healing of body and soul', language: 'greek' as const },
  { id: 'G2390', original: 'ἰάομαι', transliteration: 'iaomai', definition: 'To heal, make whole, cure — complete restoration to health', language: 'greek' as const },
  { id: 'G1411', original: 'δύναμις', transliteration: 'dunamis', definition: 'Power, miracle, mighty work — inherent divine ability, source of "dynamite"', language: 'greek' as const },
  { id: 'G5059', original: 'τέρας', transliteration: 'teras', definition: 'Wonder, marvel, prodigy — an extraordinary sign arousing amazement', language: 'greek' as const },
  { id: 'G2386', original: 'ἴαμα', transliteration: 'iama', definition: 'Healing, cure — the gift of healing, a result of divine power', language: 'greek' as const },
  // Greek — Discipleship / Following
  { id: 'G3101', original: 'μαθητής', transliteration: 'mathetes', definition: 'Disciple, learner, student — one who follows and learns from a teacher', language: 'greek' as const },
  { id: 'G190', original: 'ἀκολουθέω', transliteration: 'akoloutheo', definition: 'To follow, accompany — to walk the same path as one\'s master', language: 'greek' as const },
  { id: 'G2784', original: 'κηρύσσω', transliteration: 'kerusso', definition: 'To preach, proclaim, herald — to announce the good news publicly', language: 'greek' as const },
  { id: 'G2097', original: 'εὐαγγελίζω', transliteration: 'euangelizo', definition: 'To bring good news, evangelize — the proclamation of the gospel', language: 'greek' as const },
  { id: 'G1321', original: 'διδάσκω', transliteration: 'didasko', definition: 'To teach, instruct — imparting knowledge and forming disciples', language: 'greek' as const },
  { id: 'G3140', original: 'μαρτυρέω', transliteration: 'martureo', definition: 'To bear witness, testify — giving testimony, root of "martyr"', language: 'greek' as const },
  // Greek — Community / Church
  { id: 'G1577', original: 'ἐκκλησία', transliteration: 'ekklesia', definition: 'Church, assembly, congregation — the gathered community of believers', language: 'greek' as const },
  { id: 'G2842', original: 'κοινωνία', transliteration: 'koinonia', definition: 'Fellowship, communion, sharing — deep relational bond among believers', language: 'greek' as const },
  { id: 'G1249', original: 'διάκονος', transliteration: 'diakonos', definition: 'Servant, minister, deacon — one who serves the community', language: 'greek' as const },
  { id: 'G4245', original: 'πρεσβύτερος', transliteration: 'presbuteros', definition: 'Elder, presbyter — a mature leader in the faith community', language: 'greek' as const },
  { id: 'G1985', original: 'ἐπίσκοπος', transliteration: 'episkopos', definition: 'Overseer, bishop, guardian — one who watches over the flock', language: 'greek' as const },
  { id: 'G4151b', original: 'πνεῦμα', transliteration: 'pneuma', definition: 'Spirit, breath, wind — the Holy Spirit, the animating divine presence', language: 'greek' as const },
  { id: 'G5485b', original: 'χάρις', transliteration: 'charis', definition: 'Grace, favor, gift — unmerited divine generosity and goodwill', language: 'greek' as const },
];

export const EXTENDED_WORD_STRONGS_V8: [number, number, number, string, string, number][] = [
  // Torah references
  [5,4,44,'law','H8451',1],
  [19,119,1,'law','H8451',3],
  [19,119,97,'law','H8451',3],
  [2,20,6,'commandments','H4687',7],
  [5,6,1,'commandments','H4687',2],
  [3,18,4,'statutes','H2706',2],
  [5,16,18,'judgment','H4941',4],
  [19,19,7,'testimony','H5715',3],
  [19,119,15,'precepts','H6490',3],
  // Exile/Return
  [12,17,6,'captive','H1540',6],
  [12,25,11,'captive','H1540',5],
  [24,29,14,'captivity','H7622',3],
  [24,30,3,'captivity','H7622',2],
  [24,3,22,'return','H7725',1],
  [24,24,7,'return','H7725',2],
  [15,1,2,'build','H1129',4],
  [16,2,17,'build','H1129',3],
  [23,40,1,'comfort','H5162',1],
  [23,49,13,'comfort','H5162',4],
  // Hebrew healing
  [2,15,26,'healeth','H7495',12],
  [19,103,3,'healeth','H7495',2],
  [19,147,3,'healeth','H7495',1],
  [2,7,3,'wonders','H4159',5],
  [19,77,14,'wonders','H6381',6],
  [23,12,2,'salvation','H3444',2],
  [1,45,7,'alive','H2421',9],
  // Greek healing
  [40,4,23,'healing','G2323',8],
  [40,12,15,'healed','G2323',6],
  [42,6,19,'healed','G2390',8],
  [44,10,38,'healing','G2390',10],
  [44,1,8,'power','G1411',2],
  [46,12,10,'miracles','G1411',4],
  [44,2,22,'wonders','G5059',3],
  [46,12,9,'healing','G2386',3],
  // Discipleship
  [40,28,19,'disciples','G3101',2],
  [43,8,31,'disciples','G3101',5],
  [40,4,20,'followed','G190',5],
  [40,16,24,'follow','G190',5],
  [40,4,17,'preach','G2784',4],
  [42,4,18,'preach','G2097',5],
  [40,28,20,'teaching','G1321',1],
  [43,15,27,'witness','G3140',7],
  // Church/Community
  [40,16,18,'church','G1577',9],
  [44,2,47,'church','G1577',10],
  [44,2,42,'fellowship','G2842',4],
  [62,1,3,'fellowship','G2842',5],
  [50,1,1,'servants','G1249',2],
  [54,3,2,'bishop','G1985',2],
  [56,1,5,'elders','G4245',2],
  [44,1,8,'Spirit','G4151b',3],
  [49,2,8,'grace','G5485b',2],
];
