// Extended Strong's v9 — Worship/Praise, Prophecy/Eschatology, Nature/Creation, Suffering/Persecution
export const EXTENDED_STRONGS_V9 = [
  // Hebrew — Worship / Praise
  { id: 'H1984', original: 'הָלַל', transliteration: 'halal', definition: 'To praise, boast, shine — root of "hallelujah," exuberant praise of God', language: 'hebrew' as const },
  { id: 'H3034', original: 'יָדָה', transliteration: 'yadah', definition: 'To give thanks, praise, confess — acknowledgment with extended hand', language: 'hebrew' as const },
  { id: 'H2167', original: 'זָמַר', transliteration: 'zamar', definition: 'To sing praises, make music — instrumental worship to God', language: 'hebrew' as const },
  { id: 'H7812', original: 'שָׁחָה', transliteration: 'shachah', definition: 'To bow down, prostrate, worship — physical act of reverent submission', language: 'hebrew' as const },
  { id: 'H8426', original: 'תּוֹדָה', transliteration: 'todah', definition: 'Thanksgiving, praise, confession — a sacrifice or choir of thanksgiving', language: 'hebrew' as const },
  { id: 'H7623', original: 'שָׁבַח', transliteration: 'shabach', definition: 'To praise, laud, commend — to address in a loud tone, to shout', language: 'hebrew' as const },
  // Hebrew — Prophecy / Eschatology
  { id: 'H5012', original: 'נָבָא', transliteration: 'naba', definition: 'To prophesy, speak by inspiration — to act as a mouthpiece of God', language: 'hebrew' as const },
  { id: 'H2377', original: 'חָזוֹן', transliteration: 'chazon', definition: 'Vision, revelation, oracle — divine communication through visual means', language: 'hebrew' as const },
  { id: 'H4853', original: 'מַשָּׂא', transliteration: 'massa', definition: 'Burden, oracle, utterance — a prophetic pronouncement, often of judgment', language: 'hebrew' as const },
  { id: 'H5002', original: 'נְאֻם', transliteration: 'neum', definition: 'Declaration, utterance — "thus declares the LORD," prophetic formula', language: 'hebrew' as const },
  { id: 'H319', original: 'אַחֲרִית', transliteration: 'acharit', definition: 'End, latter days, future — the final outcome, eschatological time', language: 'hebrew' as const },
  // Hebrew — Nature / Creation
  { id: 'H8064', original: 'שָׁמַיִם', transliteration: 'shamayim', definition: 'Heaven, sky, firmament — the visible arch of the sky, abode of God', language: 'hebrew' as const },
  { id: 'H776', original: 'אֶרֶץ', transliteration: 'erets', definition: 'Earth, land, ground — the physical world, a specific territory', language: 'hebrew' as const },
  { id: 'H3220', original: 'יָם', transliteration: 'yam', definition: 'Sea, ocean, west — large body of water, symbol of chaos subdued by God', language: 'hebrew' as const },
  { id: 'H2022', original: 'הַר', transliteration: 'har', definition: 'Mountain, hill, range — place of divine encounter (Sinai, Zion, Carmel)', language: 'hebrew' as const },
  { id: 'H5104', original: 'נָהָר', transliteration: 'nahar', definition: 'River, stream, flood — life-giving water (Euphrates, Jordan), symbol of blessing', language: 'hebrew' as const },
  // Greek — Worship / Praise
  { id: 'G4352', original: 'προσκυνέω', transliteration: 'proskuneo', definition: 'To worship, do reverence — to kiss the ground before, bow in adoration', language: 'greek' as const },
  { id: 'G134', original: 'αἰνέω', transliteration: 'aineo', definition: 'To praise, extol — to express approval and admiration of God', language: 'greek' as const },
  { id: 'G1391', original: 'δόξα', transliteration: 'doxa', definition: 'Glory, splendor, honor — the visible manifestation of God\'s character', language: 'greek' as const },
  { id: 'G5568', original: 'ψαλμός', transliteration: 'psalmos', definition: 'Psalm, song of praise — a sacred song sung to musical accompaniment', language: 'greek' as const },
  { id: 'G2127', original: 'εὐλογέω', transliteration: 'eulogeo', definition: 'To bless, speak well of, praise — invoke divine favor, source of "eulogy"', language: 'greek' as const },
  // Greek — Prophecy / Eschatology
  { id: 'G4394', original: 'προφητεία', transliteration: 'propheteia', definition: 'Prophecy, prediction — the gift and act of speaking God\'s message', language: 'greek' as const },
  { id: 'G602', original: 'ἀποκάλυψις', transliteration: 'apokalupsis', definition: 'Revelation, unveiling, disclosure — uncovering of divine truth, source of "apocalypse"', language: 'greek' as const },
  { id: 'G3952', original: 'παρουσία', transliteration: 'parousia', definition: 'Coming, arrival, presence — the Second Coming of Christ', language: 'greek' as const },
  { id: 'G2250b', original: 'ἡμέρα (κυρίου)', transliteration: 'hemera (kuriou)', definition: 'Day (of the Lord) — the eschatological day of divine judgment and vindication', language: 'greek' as const },
  { id: 'G932b', original: 'βασιλεία (θεοῦ)', transliteration: 'basileia (theou)', definition: 'Kingdom (of God) — the reign and realm of God, present and future', language: 'greek' as const },
  // Greek — Suffering / Persecution
  { id: 'G3958', original: 'πάσχω', transliteration: 'pascho', definition: 'To suffer, endure, experience — suffering for Christ, source of "passion"', language: 'greek' as const },
  { id: 'G2347', original: 'θλῖψις', transliteration: 'thlipsis', definition: 'Tribulation, affliction, distress — pressure from persecution or hardship', language: 'greek' as const },
  { id: 'G1375', original: 'διωγμός', transliteration: 'diogmos', definition: 'Persecution, pursuit — systematic hostile treatment for faith', language: 'greek' as const },
  { id: 'G3144', original: 'μάρτυς', transliteration: 'martus', definition: 'Witness, martyr — one who testifies, even unto death', language: 'greek' as const },
  { id: 'G4716', original: 'σταυρός', transliteration: 'stauros', definition: 'Cross, stake — the instrument of crucifixion, symbol of redemptive suffering', language: 'greek' as const },
  { id: 'G5281', original: 'ὑπομονή', transliteration: 'hupomone', definition: 'Endurance, patience, steadfastness — perseverance under trials', language: 'greek' as const },
  { id: 'G4730', original: 'στενοχωρία', transliteration: 'stenochoria', definition: 'Distress, anguish, constriction — the narrowness of suffering', language: 'greek' as const },
  { id: 'G2346', original: 'θλίβω', transliteration: 'thlibo', definition: 'To press, afflict, oppress — to crush under burden or persecution', language: 'greek' as const },
];

// Verse references for v9 entries — [book, chapter, verse, word, strongs_id, position]
export const EXTENDED_WORD_STRONGS_V9: [number, number, number, string, string, number][] = [
  // Worship / Praise
  [19,113,1,'Praise','H1984',1],
  [19,150,1,'Praise','H1984',2],
  [19,100,4,'thankful','H3034',1],
  [19,136,1,'thanks','H3034',2],
  [19,149,3,'sing','H2167',1],
  [19,98,4,'sing','H2167',2],
  [1,24,26,'worshipped','H7812',1],
  [2,34,8,'bowed','H7812',2],
  [19,50,14,'thanksgiving','H8426',1],
  [19,107,22,'thanksgiving','H8426',2],
  [19,117,1,'Praise','H7623',1],
  [19,63,3,'praise','H7623',2],
  // Prophecy / Eschatology
  [30,2,12,'prophesy','H5012',1],
  [4,11,25,'prophesied','H5012',2],
  [20,29,18,'vision','H2377',1],
  [1,15,1,'vision','H2377',2],
  [23,13,1,'burden','H4853',1],
  [34,1,1,'burden','H4853',2],
  [1,22,16,'saith','H5002',1],
  [24,1,8,'saith','H5002',2],
  [23,2,2,'days','H319',1],
  [27,12,8,'end','H319',2],
  // Nature / Creation
  [1,1,1,'heaven','H8064',1],
  [19,19,1,'heavens','H8064',2],
  [1,1,1,'earth','H776',1],
  [23,6,3,'earth','H776',2],
  [1,1,10,'Seas','H3220',1],
  [19,95,5,'sea','H3220',2],
  [1,22,14,'mount','H2022',1],
  [19,121,1,'hills','H2022',2],
  [1,2,14,'river','H5104',1],
  [19,46,4,'river','H5104',2],
  // Greek entries
  [43,4,24,'worship','G4352',1],
  [40,2,11,'worshipped','G4352',2],
  [42,2,13,'praising','G134',1],
  [42,19,37,'praise','G134',2],
  [43,1,14,'glory','G1391',1],
  [42,2,14,'Glory','G1391',2],
  [49,5,19,'psalms','G5568',1],
  [51,3,16,'psalms','G5568',2],
  [42,1,64,'praised','G2127',1],
  [40,14,19,'blessed','G2127',2],
  [46,14,1,'prophesy','G4394',1],
  [66,19,10,'prophecy','G4394',2],
  [66,1,1,'Revelation','G602',1],
  [45,16,25,'revelation','G602',2],
  [40,24,27,'coming','G3952',1],
  [52,4,15,'coming','G3952',2],
  [44,2,20,'day','G2250b',1],
  [53,2,2,'day','G2250b',2],
  [40,6,33,'kingdom','G932b',1],
  [42,17,21,'kingdom','G932b',2],
  [40,16,21,'suffer','G3958',1],
  [60,2,21,'suffered','G3958',2],
  [40,24,21,'tribulation','G2347',1],
  [45,5,3,'tribulation','G2347',2],
  [55,3,12,'persecution','G1375',1],
  [44,13,50,'persecution','G1375',2],
  [44,1,8,'witnesses','G3144',1],
  [66,2,13,'martyr','G3144',2],
  [40,16,24,'cross','G4716',1],
  [48,6,14,'cross','G4716',2],
  [45,5,3,'patience','G5281',1],
  [66,2,2,'patience','G5281',2],
  [45,8,35,'distress','G4730',1],
  [47,6,4,'distresses','G4730',2],
  [47,1,6,'afflicted','G2346',1],
  [53,1,7,'troubled','G2346',2],
];
